name: deploy
on:
  push:
    branches:
      - 'main'
      - '!all-contributors/**'
  pull_request: {}
jobs:
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: ▶️ Run validate script
        run: npm run validate

      - name: ⬆️ Upload coverage report
        uses: codecov/codecov-action@v1

      - name: 🚀 Deploy
        # only deploy main branch on pushes
        if:
          ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.6.8
        env:
          # "HD_" is removed by akhileshns/heroku-deploy
          # from the docs:
          # > so the action can tell your environment variable apart
          # > from multiple other variables (passed by your language,
          # > github actions etc) which you probably don't want sitting
          # > in your heroku app's config vars.
          HD_CONVERT_KIT_API_KEY: ${{ secrets.CONVERT_KIT_API_KEY }}
          HD_CONVERT_KIT_API_SECRET: ${{ secrets.CONVERT_KIT_API_SECRET }}
          HD_DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          HD_GIST_BOT_TOKEN: ${{ secrets.GIST_BOT_TOKEN }}
          HD_GIST_REPO_THANKS: ${{ secrets.GIST_REPO_THANKS }}
          HD_ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          HD_ROLLBAR_ENDPOINT: ${{ secrets.ROLLBAR_ENDPOINT }}
          HD_VERIFIER_API_KEY: ${{ secrets.VERIFIER_API_KEY }}

          # no need to have husky bothering installing on heroku
          HD_HUSKY_SKIP_INSTALL: '1'
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: kcd-discord-bot
          heroku_email: me@kentcdodds.com
